"""
Test the classical pipeline on SOLVABLE instances.

Target is generated by applying K random legal moves to the initial
state, so it is reachable by construction.
"""
import sys
sys.path.insert(0, "python")

import numpy as np
from qhal.rl.planner import ClassicalPlanner
from qhal.rl.dispatch import solve


def random_solvable_instance(H, W, n_atoms, n_moves, rng):
    planner = ClassicalPlanner(H, W)

    initial = np.zeros((H, W), dtype=np.int8)
    idx = rng.choice(H * W, n_atoms, replace=False)
    initial.flat[idx] = 1

    grid = initial.copy()
    for _ in range(n_moves):
        legal = []
        for a in range(planner.n_actions):
            mv = planner.decode(a)
            if not planner.is_valid(mv):
                continue
            ng = planner.apply_move(grid, mv)
            if ng.sum() != grid.sum():
                continue
            if np.array_equal(ng, grid):
                continue
            legal.append(ng)
        if not legal:
            break
        grid = legal[rng.integers(len(legal))]

    return initial, grid


def test_grid(H, W, n_atoms, n_moves, n_trials=100, seed=42):
    rng = np.random.default_rng(seed)
    successes = 0
    solver_counts = {"astar": 0, "astar_fallback": 0, "greedy": 0, "failed": 0}

    for _ in range(n_trials):
        initial, target = random_solvable_instance(H, W, n_atoms, n_moves, rng)
        moves, ok, solver = solve(initial, target)
        if ok:
            successes += 1
        solver_counts[solver] = solver_counts.get(solver, 0) + 1

    rate = successes / n_trials
    print(f"  {H:2d}x{W:<2d}  {n_atoms:2d} atoms  {n_moves} moves  "
          f"{successes:3d}/{n_trials} = {rate:5.1%}  "
          f"(astar={solver_counts['astar']}, "
          f"greedy={solver_counts['greedy']}, "
          f"astar_fb={solver_counts['astar_fallback']}, "
          f"failed={solver_counts['failed']})")
    return rate


def main():
    print("=" * 72)
    print("  Classical pipeline — solver dispatch test")
    print("=" * 72)

    print("\n[5x5]")
    test_grid(5, 5, 3, n_moves=3)
    test_grid(5, 5, 5, n_moves=3)
    test_grid(5, 5, 5, n_moves=5)
    test_grid(5, 5, 10, n_moves=5)

    print("\n[10x10]")
    test_grid(10, 10, 5, n_moves=3, n_trials=50)
    test_grid(10, 10, 10, n_moves=5, n_trials=50)
    test_grid(10, 10, 20, n_moves=5, n_trials=50)

    print("\n[20x20]")
    test_grid(20, 20, 10, n_moves=5, n_trials=20)
    test_grid(20, 20, 20, n_moves=5, n_trials=20)

    print("\n[13x17]")
    test_grid(13, 17, 15, n_moves=5, n_trials=20)


if __name__ == "__main__":
    main()
